name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Pack Package
        run: yarn pack --filename koishi-plugin-moyu2.tgz
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: koishi-plugin-moyu2-${{ github.sha }}
          path: koishi-plugin-moyu2.tgz
